CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE person_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, birthday DATE, phone TEXT, email TEXT, avatar_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE households (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, created_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE household_members (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), household_id UUID REFERENCES households(id) ON DELETE CASCADE, person_profile_id UUID REFERENCES person_profiles(id) ON DELETE CASCADE, role TEXT DEFAULT 'member' CHECK (role IN ('admin','member')), status TEXT DEFAULT 'active' CHECK (status IN ('active','invited','pending')), invited_by UUID REFERENCES auth.users(id), joined_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(household_id, person_profile_id));
CREATE TABLE household_invites (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), household_id UUID REFERENCES households(id) ON DELETE CASCADE, token TEXT UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(16),'hex'), created_by UUID REFERENCES auth.users(id), expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '7 days', max_uses INTEGER, uses INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE person_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE households ENABLE ROW LEVEL SECURITY;
ALTER TABLE household_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE household_invites ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION get_my_person_profile_id() RETURNS UUID AS $$ SELECT id FROM person_profiles WHERE user_id = auth.uid() LIMIT 1; $$ LANGUAGE SQL STABLE SECURITY DEFINER;
CREATE OR REPLACE FUNCTION get_my_household_ids() RETURNS SETOF UUID AS $$ SELECT hm.household_id FROM household_members hm WHERE hm.person_profile_id = get_my_person_profile_id() AND hm.status = 'active'; $$ LANGUAGE SQL STABLE SECURITY DEFINER;
CREATE POLICY "pp_select" ON person_profiles FOR SELECT USING (user_id = auth.uid() OR id IN (SELECT hm.person_profile_id FROM household_members hm WHERE hm.household_id IN (SELECT get_my_household_ids())));
CREATE POLICY "pp_insert" ON person_profiles FOR INSERT WITH CHECK (user_id = auth.uid() OR user_id IS NULL);
CREATE POLICY "pp_update" ON person_profiles FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "hh_select" ON households FOR SELECT USING (id IN (SELECT get_my_household_ids()));
CREATE POLICY "hh_insert" ON households FOR INSERT WITH CHECK (created_by = auth.uid());
CREATE POLICY "hm_select" ON household_members FOR SELECT USING (household_id IN (SELECT get_my_household_ids()));
CREATE POLICY "hm_insert" ON household_members FOR INSERT WITH CHECK (household_id IN (SELECT get_my_household_ids()) OR person_profile_id = get_my_person_profile_id());
CREATE POLICY "hm_update" ON household_members FOR UPDATE USING (household_id IN (SELECT get_my_household_ids()));
CREATE POLICY "hi_select" ON household_invites FOR SELECT USING (true);
CREATE POLICY "hi_insert" ON household_invites FOR INSERT WITH CHECK (household_id IN (SELECT get_my_household_ids()));
CREATE POLICY "hi_update" ON household_invites FOR UPDATE USING (true);